/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javabilet;
import java.sql.Date;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
/**
 *
 * @author kadirbusra
 */
public class biletguncelle extends javax.swing.JFrame {

    /**
     * Creates new form biletguncelle2
     */
    public biletguncelle() {
        initComponents();
         hedef();
        guzergah();
        guncelle();
        otodetays();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guncelle = new javax.swing.JComboBox<>();
        yas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        telefon = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        koltuk = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        otoguzergah = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        hedef = new javax.swing.JComboBox<>();
        ucret = new javax.swing.JTextField();
        ad = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        otono = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        tarihi = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        cinsiyet = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bilet Güncelle");
        setResizable(false);

        guncelle.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        guncelle.setForeground(new java.awt.Color(102, 102, 102));
        guncelle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz" }));

        yas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        yas.setForeground(new java.awt.Color(255, 51, 51));
        yas.setCaretColor(new java.awt.Color(255, 102, 102));
        yas.setOpaque(false);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Telefon");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 153, 153));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javabilet/resimler/eraser.png"))); // NOI18N
        jButton3.setText("Temizle");
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        telefon.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        telefon.setForeground(new java.awt.Color(255, 51, 51));
        telefon.setCaretColor(new java.awt.Color(255, 102, 102));
        telefon.setOpaque(false);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Koltuk");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Hedef");

        koltuk.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        koltuk.setForeground(new java.awt.Color(255, 51, 51));
        koltuk.setCaretColor(new java.awt.Color(255, 102, 102));
        koltuk.setOpaque(false);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Güzergah");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Ücret");

        otoguzergah.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        otoguzergah.setForeground(new java.awt.Color(102, 102, 102));
        otoguzergah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz" }));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Otobüs");

        hedef.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        hedef.setForeground(new java.awt.Color(102, 102, 102));
        hedef.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz" }));

        ucret.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ucret.setForeground(new java.awt.Color(255, 51, 51));
        ucret.setCaretColor(new java.awt.Color(255, 102, 102));
        ucret.setOpaque(false);

        ad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ad.setForeground(new java.awt.Color(255, 51, 51));
        ad.setCaretColor(new java.awt.Color(255, 102, 102));
        ad.setOpaque(false);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Tarih");

        otono.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        otono.setForeground(new java.awt.Color(102, 102, 102));
        otono.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz" }));
        otono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otonoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Adı Soyadı");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Yaş");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Güncelleme Kimliği");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 153, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javabilet/resimler/floppy-disc.png"))); // NOI18N
        jButton1.setText("Kaydet");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Cinsiyet");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 153, 153));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javabilet/resimler/login1.png"))); // NOI18N
        jButton2.setText("Admin Paneli");
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(153, 153, 153));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javabilet/resimler/sofor1.png"))); // NOI18N
        jButton4.setText("Anasayfa");
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        cinsiyet.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cinsiyet.setForeground(new java.awt.Color(102, 102, 102));
        cinsiyet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Erkek", "Bayan" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ad)
                    .addComponent(telefon)
                    .addComponent(yas)
                    .addComponent(guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hedef, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(otoguzergah, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(otono, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(22, 22, 22)
                        .addComponent(cinsiyet, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ucret)
                            .addComponent(koltuk, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tarihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(ucret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(koltuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(otono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel6)
                            .addComponent(otoguzergah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(telefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(hedef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(cinsiyet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void mesaj(String mesaz,String bilgi)
{       
 JOptionPane.showMessageDialog(null,mesaz,bilgi,JOptionPane.INFORMATION_MESSAGE);

}
public void uyari(String mesaz,String bilgi)
{       
 JOptionPane.showMessageDialog(null,mesaz,bilgi,JOptionPane.WARNING_MESSAGE);

}
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         ad.setText("");
            yas.setText("");
            guncelle.setSelectedItem("Seçiniz");    
             telefon.setText("");
            otono.setSelectedItem("Seçiniz");
             otoguzergah.setSelectedItem("Seçiniz");
              hedef.setSelectedItem("Seçiniz");
            koltuk.setText("");
            ucret.setText(""); 
           cinsiyet.setSelectedItem("Erkek");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void otonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otonoActionPerformed

    }//GEN-LAST:event_otonoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String adi=ad.getText();
        String yasi=yas.getText();
        String guncell=(String)guncelle.getSelectedItem();
        String tel=telefon.getText();
        String bussno=(String)otono.getSelectedItem();
        java.util.Date tarih=tarihi.getDate();
        SimpleDateFormat formats=new SimpleDateFormat("dd-MM-yyyy");
        String dates=formats.format(tarih);
        String busguz=(String)otoguzergah.getSelectedItem();
        String bushedef=(String)hedef.getSelectedItem();
        String koltuks=koltuk.getText();
        String fiyati=ucret.getText();
        String cins=(String)cinsiyet.getSelectedItem();
        try{

            Class.forName("com.mysql.jdbc.Driver");
          String databaseURL="jdbc:mysql://sql11.freesqldatabase.com/sql11229067";
            Connection bagla= DriverManager.getConnection(databaseURL, "sql11229067", "FBJKAQRyG8");
            Statement stat=bagla.createStatement();
            if("".equals(adi) || "".equals(yasi) || "".equals(guncell) || "".equals(tel) || "Seçiniz".equals(bussno) || "Seçiniz".equals(busguz) || "Seçiniz".equals(bushedef) || "".equals(koltuks) || "".equals(fiyati)){
            
            uyari("Lütfen Alanları Eksiksiz Doldurunuz ","Hata");
            
          ad.setText("");
            yas.setText("");
            guncelle.setSelectedItem("Seçiniz");     
             telefon.setText("");
            otono.setSelectedItem("Seçiniz");
             otoguzergah.setSelectedItem("Seçiniz");
              hedef.setSelectedItem("Seçiniz");
            koltuk.setText("");
            ucret.setText(""); 
            cinsiyet.setSelectedItem("Erkek");
            }
            else{
            String secim="select * from bilet where guncelle='"+guncell+"'";

            ResultSet b= stat.executeQuery(secim);

            while(b.next())
            {
                String veriler = "update bilet set ad='"+adi+"',yas='"+yasi+"',telefon='"+tel+"',otono='"+bussno+"',koltuk='"+koltuks+"',otoguzergah='"+busguz+"',hedef='"+bushedef+"',tarihi='"+dates+"',ucret='"+fiyati+"',cinsiyet='"+cins+"' where guncelle='"+guncell+"'";
                stat.executeUpdate(veriler);
                mesaj(guncell+" Kodlu Bilet Güncellendi","Uyarı");

            }
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        adminkontrol a=new adminkontrol();
        a.setLocationRelativeTo(null);
        a.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
        anasayfa a=new anasayfa();
        a.setLocationRelativeTo(null);
        a.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

     public void guncelle(){
try{
     Class.forName("com.mysql.jdbc.Driver");
          String databaseURL="jdbc:mysql://sql11.freesqldatabase.com/sql11229067";
            Connection bagla= DriverManager.getConnection(databaseURL, "sql11229067", "FBJKAQRyG8");
             Statement stat=bagla.createStatement();

            String secim="select guncelle from bilet";
            ResultSet b= stat.executeQuery(secim);
            while(b.next())
            {
            guncelle.addItem(b.getString("guncelle"));
            }
            
}

catch(Exception e){
System.out.println();
}
    }
      public void otodetays(){
try{
     Class.forName("com.mysql.jdbc.Driver");
          String databaseURL="jdbc:mysql://sql11.freesqldatabase.com/sql11229067";
            Connection bagla= DriverManager.getConnection(databaseURL, "sql11229067", "FBJKAQRyG8");
             Statement stat=bagla.createStatement();

            String secim="select otono from otodetay";
            ResultSet b= stat.executeQuery(secim);
            while(b.next())
            {
            otono.addItem(b.getString("otono"));
            }
            
}

catch(Exception e){
System.out.println();
}

    }
     public void hedef(){
try{
     Class.forName("com.mysql.jdbc.Driver");
          String databaseURL="jdbc:mysql://sql11.freesqldatabase.com/sql11229067";
            Connection bagla= DriverManager.getConnection(databaseURL, "sql11229067", "FBJKAQRyG8");
             Statement stat=bagla.createStatement();

            String secim="select hedef from hedef";
            ResultSet b= stat.executeQuery(secim);
            while(b.next())
            {
            hedef.addItem(b.getString("hedef"));
            }
            
}

catch(Exception e){
System.out.println();
}

    }
     public void guzergah(){
try{
     Class.forName("com.mysql.jdbc.Driver");
          String databaseURL="jdbc:mysql://sql11.freesqldatabase.com/sql11229067";
            Connection bagla= DriverManager.getConnection(databaseURL, "sql11229067", "FBJKAQRyG8");
             Statement stat=bagla.createStatement();

            String secim="select otoguzergah from guzergah";
            ResultSet b= stat.executeQuery(secim);
            while(b.next())
            {
            otoguzergah.addItem(b.getString("otoguzergah"));
            }
            
}

catch(Exception e){
System.out.println();
}

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(biletguncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(biletguncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(biletguncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(biletguncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new biletguncelle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad;
    private javax.swing.JComboBox<String> cinsiyet;
    private javax.swing.JComboBox<String> guncelle;
    private javax.swing.JComboBox<String> hedef;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField koltuk;
    private javax.swing.JComboBox<String> otoguzergah;
    private javax.swing.JComboBox<String> otono;
    private org.jdesktop.swingx.JXDatePicker tarihi;
    private javax.swing.JTextField telefon;
    private javax.swing.JTextField ucret;
    private javax.swing.JTextField yas;
    // End of variables declaration//GEN-END:variables
}
