/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javabilet;
import java.text.SimpleDateFormat;
import javax.swing.JTextField;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
/**
 *
 * @author kadirbusra
 */
public class seferguncelle extends javax.swing.JFrame {

    /**
     * Creates new form seferguncelle2
     */
    public seferguncelle() {
        initComponents();
         otodetays();
          guzergah();
          hedef();
          otoara();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        otoguzergah = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        hareket = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        anasayfa1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tarihi = new org.jdesktop.swingx.JXDatePicker();
        otono = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        otoid = new javax.swing.JComboBox<>();
        otohedef = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        zamani = new javax.swing.JLabel();
        fiyat = new javax.swing.JLabel();
        koltuk = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sefer Güncelle");
        setPreferredSize(new java.awt.Dimension(787, 414));
        setResizable(false);

        otoguzergah.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        otoguzergah.setForeground(new java.awt.Color(102, 102, 102));
        otoguzergah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz" }));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 153, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javabilet/resimler/floppy-disc.png"))); // NOI18N
        jButton1.setText("Kaydet");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 153, 153));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javabilet/resimler/eraser.png"))); // NOI18N
        jButton2.setText("Temizle");
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        hareket.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        hareket.setForeground(new java.awt.Color(102, 102, 102));
        hareket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gidiş", "Dönüş" }));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Hareket");
        jLabel5.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Hareket Zamanı");

        anasayfa1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        anasayfa1.setForeground(new java.awt.Color(153, 153, 153));
        anasayfa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javabilet/resimler/login1.png"))); // NOI18N
        anasayfa1.setText("Yönetici Paneli");
        anasayfa1.setContentAreaFilled(false);
        anasayfa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anasayfa1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Yeni Otobüs");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Otobüs Seçimi");

        otono.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        otono.setForeground(new java.awt.Color(102, 102, 102));
        otono.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz" }));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Güzergah");

        otoid.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        otoid.setForeground(new java.awt.Color(102, 102, 102));
        otoid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz" }));
        otoid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otoidActionPerformed(evt);
            }
        });

        otohedef.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        otohedef.setForeground(new java.awt.Color(102, 102, 102));
        otohedef.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz" }));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Hedef");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 153, 153));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javabilet/resimler/sofor1.png"))); // NOI18N
        jButton3.setText("Anasayfa");
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 102, 102));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javabilet/resimler/rotation.png"))); // NOI18N
        jButton4.setText("Yenile");
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(316, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(zamani)
                        .addGap(134, 134, 134))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(fiyat)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(anasayfa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(koltuk)
                            .addComponent(jButton4))
                        .addGap(184, 184, 184))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(53, 53, 53)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(otoid, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(otohedef, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(otoguzergah, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(100, 100, 100))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(55, 55, 55)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addGap(63, 63, 63)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hareket, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(otono, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(171, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(koltuk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fiyat)
                        .addGap(64, 64, 64)
                        .addComponent(zamani)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(anasayfa1)
                            .addComponent(jButton3))
                        .addGap(39, 39, 39))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(otono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(32, 32, 32)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(otoid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(hareket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(3, 3, 3)))
                    .addGap(26, 26, 26)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(otoguzergah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(tarihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(otohedef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(174, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void mesaj(String mesaz,String bilgi)
{       
 JOptionPane.showMessageDialog(null,mesaz,bilgi,JOptionPane.INFORMATION_MESSAGE);

}
public void uyari(String mesaz,String bilgi)
{       
 JOptionPane.showMessageDialog(null,mesaz,bilgi,JOptionPane.WARNING_MESSAGE);

}

 public void otodetays(){
try{
     Class.forName("com.mysql.jdbc.Driver");
          String databaseURL="jdbc:mysql://sql11.freesqldatabase.com/sql11229067";
            Connection bagla= DriverManager.getConnection(databaseURL, "sql11229067", "FBJKAQRyG8");
             Statement stat=bagla.createStatement();

            String secim="select otoid from otobus";
            ResultSet b= stat.executeQuery(secim);
            while(b.next())
            {
            otoid.addItem(b.getString("otoid"));
            }
            
}
catch(Exception e){
System.out.println();
}

}
       public void otoara(){
try{
     Class.forName("com.mysql.jdbc.Driver");
           String databaseURL="jdbc:mysql://sql11.freesqldatabase.com/sql11229067";
            Connection bagla= DriverManager.getConnection(databaseURL, "sql11229067", "FBJKAQRyG8");
             Statement stat=bagla.createStatement();

            String secim="select otono from otodetay";
            ResultSet b= stat.executeQuery(secim);
            while(b.next())
            {
            otono.addItem(b.getString("otono"));
            }
            
}
catch(Exception e){
System.out.println();
}

}
public void guzergah(){
try{
     Class.forName("com.mysql.jdbc.Driver");
          String databaseURL="jdbc:mysql://sql11.freesqldatabase.com/sql11229067";
            Connection bagla= DriverManager.getConnection(databaseURL, "sql11229067", "FBJKAQRyG8");
             Statement stat=bagla.createStatement();

            String secim="select otoguzergah from guzergah";
            ResultSet b= stat.executeQuery(secim);
            while(b.next())
            {
            otoguzergah.addItem(b.getString("otoguzergah"));
            }
            
}
catch(Exception e){
System.out.println();
}

}
public void hedef(){
try{
     Class.forName("com.mysql.jdbc.Driver");
           String databaseURL="jdbc:mysql://sql11.freesqldatabase.com/sql11229067";
            Connection bagla= DriverManager.getConnection(databaseURL, "sql11229067", "FBJKAQRyG8");
             Statement stat=bagla.createStatement();

            String secim="select hedef from hedef";
            ResultSet b= stat.executeQuery(secim);
            while(b.next())
            {
            otohedef.addItem(b.getString("hedef"));
            }
            
}
catch(Exception e){
System.out.println();
}
}
    private void otoidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otoidActionPerformed

    }//GEN-LAST:event_otoidActionPerformed

    private void anasayfa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anasayfa1ActionPerformed
        dispose();
        adminkontrol a=new adminkontrol();
        a.setLocationRelativeTo(null);
        a.setVisible(true);
    }//GEN-LAST:event_anasayfa1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          hareket.setSelectedItem("Gidiş");
         otoguzergah.setSelectedItem("Seçiniz");
        otohedef.setSelectedItem("Seçiniz");
        otono.setSelectedItem("Seçiniz");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String bussno=(String)otono.getSelectedItem();
        String bussid=(String)otoid.getSelectedItem();
        String bushareket=(String)hareket.getSelectedItem();
        String busguz=(String)otoguzergah.getSelectedItem();
        String bushedef=(String)otohedef.getSelectedItem();

        java.util.Date tarih=tarihi.getDate();
        SimpleDateFormat formats=new SimpleDateFormat("dd-MM-yyyy");
        String dates=formats.format(tarih);
        String zaman=zamani.getText();
        String fiyati=fiyat.getText();
        String koltukk=koltuk.getText();
        try{

            Class.forName("com.mysql.jdbc.Driver");
          String databaseURL="jdbc:mysql://sql11.freesqldatabase.com/sql11229067";
            Connection bagla= DriverManager.getConnection(databaseURL, "sql11229067", "FBJKAQRyG8");
            Statement stat=bagla.createStatement();
              if("Seçiniz".equals(bussno) || "Seçiniz".equals(bushedef) || "Seçiniz".equals(busguz)){
            
            uyari("Lütfen Alanları Eksiksiz Doldurunuz ","Hata");
           
        hareket.setSelectedItem("Gidiş");
         otoguzergah.setSelectedItem("Seçiniz");
        otohedef.setSelectedItem("Seçiniz");
        otono.setSelectedItem("Seçiniz");
              }
              else{
            String secim="select * from otodetay where otono='"+bussno+"'";

            ResultSet b= stat.executeQuery(secim);

            while(b.next())
            {
                String veriler = "update  otodetay set otoguzergah='"+busguz+"',otohedef='"+bushedef+"',hareket='"+bushareket+"',tarihi='"+dates+"',zamani='"+zaman+"',fiyat='"+fiyati+"',koltuk='"+koltukk+"',otono='"+bussid+"' where otono='"+bussno+"'";

                stat.executeUpdate(veriler);

                mesaj("Otobüs Seferi Başarı İle Güncellendi","Uyarı");

            }
              }
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        anasayfa a=new anasayfa();
        a.setLocationRelativeTo(null);
        a.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         dispose();
        seferguncelle a=new seferguncelle();
        a.setLocationRelativeTo(null);
        a.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seferguncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seferguncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seferguncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seferguncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new seferguncelle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anasayfa1;
    private javax.swing.JLabel fiyat;
    private javax.swing.JComboBox<String> hareket;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel koltuk;
    private javax.swing.JComboBox<String> otoguzergah;
    private javax.swing.JComboBox<String> otohedef;
    private javax.swing.JComboBox<String> otoid;
    private javax.swing.JComboBox<String> otono;
    private org.jdesktop.swingx.JXDatePicker tarihi;
    private javax.swing.JLabel zamani;
    // End of variables declaration//GEN-END:variables
}
