/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javabilet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import static java.time.zone.ZoneRulesProvider.refresh;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author kadirbusra
 */
public class sefersil extends javax.swing.JFrame {

    /**
     * Creates new form sefersil
     */
    public sefersil() {
        initComponents();
        otodetays();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("sql11229067?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        otodetayQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT o FROM Otodetay o");
        otodetayList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : otodetayQuery.getResultList();
        jLabel2 = new javax.swing.JLabel();
        otono = new javax.swing.JComboBox<>();
        anasayfa1 = new javax.swing.JButton();
        tarihi = new org.jdesktop.swingx.JXDatePicker();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        yenile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sefer Silme İşlemi");
        setPreferredSize(new java.awt.Dimension(787, 414));
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Otobüs No");

        otono.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        otono.setForeground(new java.awt.Color(102, 102, 102));
        otono.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz" }));
        otono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otonoActionPerformed(evt);
            }
        });

        anasayfa1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        anasayfa1.setForeground(new java.awt.Color(153, 153, 153));
        anasayfa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javabilet/resimler/login1.png"))); // NOI18N
        anasayfa1.setText("Yönetici Paneli");
        anasayfa1.setContentAreaFilled(false);
        anasayfa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anasayfa1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Hareket Zamanı");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 153, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javabilet/resimler/Delete_Icon (32 x 26).png"))); // NOI18N
        jButton1.setText("Seçilen Seferi Sil");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        yenile.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        yenile.setForeground(new java.awt.Color(153, 153, 153));
        yenile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javabilet/resimler/rotation.png"))); // NOI18N
        yenile.setText("Tabloyu Yenile");
        yenile.setContentAreaFilled(false);
        yenile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yenileActionPerformed(evt);
            }
        });

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, otodetayList, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${otono}"));
        columnBinding.setColumnName("Otono");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${otoguzergah}"));
        columnBinding.setColumnName("Otoguzergah");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${otohedef}"));
        columnBinding.setColumnName("Otohedef");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tarihi}"));
        columnBinding.setColumnName("Tarihi");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${hareket}"));
        columnBinding.setColumnName("Hareket");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(otono, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(anasayfa1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                        .addComponent(yenile)
                        .addGap(19, 19, 19)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(otono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tarihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(yenile)
                    .addComponent(anasayfa1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void mesaj(String mesaz,String bilgi)
{       
 JOptionPane.showMessageDialog(null,mesaz,bilgi,JOptionPane.INFORMATION_MESSAGE);

}
public void uyari(String mesaz,String bilgi)
{       
 JOptionPane.showMessageDialog(null,mesaz,bilgi,JOptionPane.WARNING_MESSAGE);

}
public void otodetays(){
try{
     Class.forName("com.mysql.jdbc.Driver");
          String databaseURL="jdbc:mysql://sql11.freesqldatabase.com/sql11229067";
            Connection bagla= DriverManager.getConnection(databaseURL, "sql11229067", "FBJKAQRyG8");
             Statement stat=bagla.createStatement();

            String secim="select otono from otodetay";
            ResultSet b= stat.executeQuery(secim);
            while(b.next())
            {
            otono.addItem(b.getString("otono"));
            }
            
}
catch(Exception e){
System.out.println();
}}
    private void otonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otonoActionPerformed

    }//GEN-LAST:event_otonoActionPerformed

    private void anasayfa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anasayfa1ActionPerformed
        dispose();
        adminkontrol a=new adminkontrol();
        a.setLocationRelativeTo(null);
        a.setVisible(true);
    }//GEN-LAST:event_anasayfa1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String bussno=(String)otono.getSelectedItem();
        java.util.Date tarih=tarihi.getDate();
        SimpleDateFormat formats=new SimpleDateFormat("dd-MM-yyyy");
        String dates=formats.format(tarih);
        try{

            Class.forName("com.mysql.jdbc.Driver");
            String databaseURL="jdbc:mysql://sql11.freesqldatabase.com/sql11229067";
            Connection bagla= DriverManager.getConnection(databaseURL, "sql11229067", "FBJKAQRyG8");
            Statement stat=bagla.createStatement();
            if("Seçiniz".equals(bussno)){

                uyari("Lütfen Silinecek Seferi Seçiniz ","Hata");

                otono.setSelectedItem("Seçiniz");
            }

            String secim="select * from otodetay where otono='"+bussno+"' and tarihi='"+dates+"'";

            ResultSet b= stat.executeQuery(secim);

            while(b.next())
            {

                String veriler = "delete from otodetay where otono='"+bussno+"' and tarihi='"+dates+"'";
                String bilet = "delete from bilet where otono='"+bussno+"'" ;
                stat.execute(veriler);
                stat.execute(bilet);
                mesaj("Otobüs Seferi Başarı İle Silindi","Uyarı");

            }

        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void yenileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yenileActionPerformed
        dispose();
        sefersil a=new sefersil();
        a.setLocationRelativeTo(null);
        a.setVisible(true);
    }//GEN-LAST:event_yenileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sefersil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sefersil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sefersil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sefersil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sefersil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anasayfa1;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.util.List<javabilet.Otodetay> otodetayList;
    private javax.persistence.Query otodetayQuery;
    private javax.swing.JComboBox<String> otono;
    private org.jdesktop.swingx.JXDatePicker tarihi;
    private javax.swing.JButton yenile;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
