/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javabilet;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author kadirbusra
 */
public class yenisefer extends javax.swing.JFrame {

    /**
     * Creates new form yenisefer2
     */
    public yenisefer() {
        initComponents();
     
        otodetays();
          guzergah();
          hedef();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        anasayfa = new javax.swing.JButton();
        tarihi = new org.jdesktop.swingx.JXDatePicker();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        otoguzergah = new javax.swing.JComboBox<>();
        hedef = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        hareket = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        otoid = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        zamani = new javax.swing.JLabel();
        fiyat = new javax.swing.JLabel();
        koltuk = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Yeni Sefer Ekle");
        setPreferredSize(new java.awt.Dimension(787, 414));
        setResizable(false);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 153, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javabilet/resimler/floppy-disc.png"))); // NOI18N
        jButton1.setText("Kaydet");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        anasayfa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        anasayfa.setForeground(new java.awt.Color(153, 153, 153));
        anasayfa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javabilet/resimler/login1.png"))); // NOI18N
        anasayfa.setText("Yönetici Paneli");
        anasayfa.setContentAreaFilled(false);
        anasayfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anasayfaActionPerformed(evt);
            }
        });

        tarihi.setForeground(new java.awt.Color(255, 102, 51));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Hareket Zamanı");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 153, 153));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javabilet/resimler/eraser.png"))); // NOI18N
        jButton2.setText("Temizle");
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        otoguzergah.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        otoguzergah.setForeground(new java.awt.Color(102, 102, 102));
        otoguzergah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz" }));

        hedef.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        hedef.setForeground(new java.awt.Color(102, 102, 102));
        hedef.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz" }));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Otobüs No");

        hareket.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        hareket.setForeground(new java.awt.Color(102, 102, 102));
        hareket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gidiş", "Dönüş" }));
        hareket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hareketActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Güzergah");

        otoid.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        otoid.setForeground(new java.awt.Color(102, 102, 102));
        otoid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz" }));
        otoid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otoidActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Hedef");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Hareket");
        jLabel5.setToolTipText("");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 153, 153));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javabilet/resimler/sofor1.png"))); // NOI18N
        jButton3.setText("Anasayfa");
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(235, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(koltuk, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(32, 32, 32)
                                .addComponent(tarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(77, 77, 77)
                                .addComponent(hareket, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(127, 127, 127))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(anasayfa)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fiyat)
                            .addComponent(zamani)))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4))
                    .addGap(57, 57, 57)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(otoguzergah, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(otoid, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hedef, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(430, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(hareket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tarihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(40, 40, 40)
                .addComponent(zamani)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(fiyat)
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1)
                                    .addComponent(jButton2))
                                .addGap(51, 51, 51))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(anasayfa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17)))
                .addComponent(koltuk)
                .addGap(18, 57, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(otoid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(28, 28, 28)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(otoguzergah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(28, 28, 28)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hedef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addContainerGap(191, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void mesaj(String mesaz,String bilgi)
{       
 JOptionPane.showMessageDialog(null,mesaz,bilgi,JOptionPane.INFORMATION_MESSAGE);

}
public void uyari(String mesaz,String bilgi)
{       
 JOptionPane.showMessageDialog(null,mesaz,bilgi,JOptionPane.WARNING_MESSAGE);

}
public void sil(){

}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String bussno=(String)otoid.getSelectedItem();
        String bushareket=(String)hareket.getSelectedItem();
        String busguz=(String)otoguzergah.getSelectedItem();
        String bushedef=(String)hedef.getSelectedItem();

        java.util.Date tarih=tarihi.getDate();
        SimpleDateFormat formats=new SimpleDateFormat("dd-MM-yyyy");
        String dates=formats.format(tarih);
        String zaman=fiyat.getText();
        String fiyati=fiyat.getText();
        String koltukk=koltuk.getText();

        try{

            Class.forName("com.mysql.jdbc.Driver");
           String databaseURL="jdbc:mysql://sql11.freesqldatabase.com/sql11229067";
            Connection bagla= DriverManager.getConnection(databaseURL, "sql11229067", "FBJKAQRyG8");
            Statement stat=bagla.createStatement();
              if("Seçiniz".equals(bussno) || "Seçiniz".equals(bushedef) || "Seçiniz".equals(busguz)){
            
            uyari("Lütfen Alanları Eksiksiz Doldurunuz ","Hata");
             otoid.setSelectedItem("Seçiniz");
        hareket.setSelectedItem("Gidiş");
         otoguzergah.setSelectedItem("Seçiniz");
        hedef.setSelectedItem("Seçiniz");
              }
              else{
            String secim="select * from otodetay where otono='"+bussno+"' and tarihi='"+dates+"'";

            ResultSet b= stat.executeQuery(secim);

            if(b.next()==true)
            {
                uyari(" Bu Otobüse Ait Sefer Günü Saten Var ","Hata");

            }
            else
            {

                String veriler = "insert into otodetay values(null,'"+bussno+"','"+busguz+"','"+bushedef+"','"+bushareket+"','"+dates+"','"+zaman+"','"+fiyati+"','"+koltukk+"')";
                stat.executeUpdate(veriler);
                mesaj("Yeni Otobüs Seferi Oluşturuldu","Uyarı");

            }
        } }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void otodetays(){
try{
     Class.forName("com.mysql.jdbc.Driver");
          String databaseURL="jdbc:mysql://sql11.freesqldatabase.com/sql11229067";
            Connection bagla= DriverManager.getConnection(databaseURL, "sql11229067", "FBJKAQRyG8");
             Statement stat=bagla.createStatement();

            String secim="select otoid from otobus";
            ResultSet b= stat.executeQuery(secim);
            while(b.next())
            {
            otoid.addItem(b.getString("otoid"));
            }
            
}
catch(Exception e){
System.out.println();
}

}
public void guzergah(){
try{
     Class.forName("com.mysql.jdbc.Driver");
           String databaseURL="jdbc:mysql://sql11.freesqldatabase.com/sql11229067";
            Connection bagla= DriverManager.getConnection(databaseURL, "sql11229067", "FBJKAQRyG8");
             Statement stat=bagla.createStatement();

            String secim="select otoguzergah from guzergah";
            ResultSet b= stat.executeQuery(secim);
            while(b.next())
            {
            otoguzergah.addItem(b.getString("otoguzergah"));
            }
            
}
catch(Exception e){
System.out.println();
}

}
         public void hedef(){
        try{
     Class.forName("com.mysql.jdbc.Driver");
           String databaseURL="jdbc:mysql://sql11.freesqldatabase.com/sql11229067";
            Connection bagla= DriverManager.getConnection(databaseURL, "sql11229067", "FBJKAQRyG8");
             Statement stat=bagla.createStatement();

            String secim="select hedef from hedef";
            ResultSet b= stat.executeQuery(secim);
            while(b.next())
            {
            hedef.addItem(b.getString("hedef"));
            }
            
}
catch(Exception e){
System.out.println();
}
}
    
    private void anasayfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anasayfaActionPerformed
        dispose();
        adminkontrol a=new adminkontrol();
        a.setLocationRelativeTo(null);
        a.setVisible(true);
    }//GEN-LAST:event_anasayfaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       otoid.setSelectedItem("Seçiniz");
        hareket.setSelectedItem("Gidiş");
         otoguzergah.setSelectedItem("Seçiniz");
        hedef.setSelectedItem("Seçiniz");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void hareketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hareketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hareketActionPerformed

    private void otoidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otoidActionPerformed

    }//GEN-LAST:event_otoidActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        anasayfa a=new anasayfa();
        a.setLocationRelativeTo(null);
        a.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(yenisefer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(yenisefer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(yenisefer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yenisefer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new yenisefer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anasayfa;
    private javax.swing.JLabel fiyat;
    private javax.swing.JComboBox<String> hareket;
    private javax.swing.JComboBox<String> hedef;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel koltuk;
    private javax.swing.JComboBox<String> otoguzergah;
    private javax.swing.JComboBox<String> otoid;
    private org.jdesktop.swingx.JXDatePicker tarihi;
    private javax.swing.JLabel zamani;
    // End of variables declaration//GEN-END:variables
}
